### ISSUE TITLE
Just some examples

### ISSUE THREAD

**Issue by ejemba** [jezek/funson#1]
Hi @jezek 

I'm just curious on how you use funson !

Can you provide some examples :) 

Thank you

**Comment by jezek** [comment]
@ejemba I've added stuff to readme, funson executable and some examples. I will try to add more examples, describe and rethink or add functions continuously, but for the sake of this issue, is it enough?

**Comment by ejemba** [comment]
Thank you @jezek I'll have a look
All I can tell, is that looks similar than a lisp in a way !
